version: '3.1'

services:

  app:
    build: .
    links:
      - "db:database"
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: todoapp
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo